project:
  proj_dir: project/
  model_dir: models/
  cfg_fname: configs.yml
  train_log:
    path: train.log
    screen_intvl: 10
    headers: {Loss: ':3.4f', Baseline: ':3.4f', Mean_Dist: ':3.4f',
      bkb_grad: ':3.2f', head_grad: ':3.2f'}
  val_log:
    path: val.log
    screen_intvl: 1
    headers: {Loss: ':3.4f', Baseline: ':3.4f', Fuse_Dist: ':3.4f',
      Selected: ':3.4f'}
  eval_log:
    path: eval.log
    screen_intvl: 1
    headers: {Loss: ':3.4f', Baseline: ':3.4f', Fuse_Dist: ':3.4f',
      Selected: ':3.4f'}
  val_intvl: 40
  eval_intvl: 40
  save_iters: [50000,]
data:
  base:
    dataset:
      type: PenstateDatasetAM
      ann_path: data/penstate/data_16k.lst
      gender: F
      seed: 666
      train_seed: -1
      split: [7, 1, 1, 1]
      duration: [26, 28]
      sample_rate: 16000
      measure_indices: [12]
      norm_type: l2
    dataloader:
      type: DataLoader
      batch_size: 1
      num_workers: 1
      pin_memory: false
      shuffle: false
      drop_last: false
  train:
    dataset:
      mode: train
      duration: [6, 8]
    dataloader:
      batch_size: 64
      num_workers: 4
      shuffle: false
      drop_last: true
  val:
    dataset: {mode: val}
  eval:
    dataset: {mode: eval}
model:
  base:
    optimizer: {type: SGD, lr: 0.1, momentum: 0.9, weight_decay: 0.001}
    # optimizer: {type: Adam, lr: 0.001}
    scheduler:
      type: MultiStepLR
      milestones: [16000, 24000, 28000]
      gamma: 0.1
  backbone:
    net:
      type: VoiceFeatNet
      sample_rate: 16000
      n_fft: 512
      n_mels: 64
      cnn_channel: 64
      feat_dim: 64
  head:
    net:
      type: AvgPool_Linear
      output_dim: 1
