project:
  proj_dir: project/
  model_dir: models/
  cfg_fname: configs.yml
  train_log:
    path: train.log
    screen_intvl: 20
    headers: {
      Loss: ':3.4f',
      d_95: ':3.3f',
      d_05: ':3.3f',
      p_95: ':3.3f',
      p_05: ':3.3f',
      bkb_grad: ':2.3f',
      head_grad: ':2.3f',
    }
  val_log:
    path: val.log
    screen_intvl: 1
    headers: {
      Loss: ':3.4f',
      d_95: ':3.3f',
      d_05: ':3.3f',
      p_95: ':3.3f',
      p_05: ':3.3f',
    }
  val_intvl: 40
  save_iters: [2000, 4000, 6000, 8000]
data:
  base:
    dataset: {
      type: PenstateDataset,
      ann_file: data/data_16k.lst,
      sample_rate: 16000,
      seed: 666,
      split: 1000,
    }
    dataloader: {
      type: DataLoader,
      num_workers: 4,
      pin_memory: false,
    }
  train:
    dataset:
      test_mode: false
      duration: [16, 18]
    dataloader: {
      batch_size: 128,
      shuffle: true,
      drop_last: true,
    }
  val:
    dataset:
      test_mode: true
      duration: [16, 18]
    dataloader: {
      batch_size: 1,
      num_workers: 1,
      shuffle: false,
      drop_last: false,
    }
model:
  base:
    net: {}
    optimizer: {
      type: SGD,
      lr: 1.0,
      momentum: 0.9,
      weight_decay: 0.0001
      #type: Adam,
      #lr: 0.001,
    }
    scheduler:
      type: MultiStepLR
      #milestones: [4000, 6000, 8000]
      milestones: [8000]
      gamma: 0.1
  backbone:
    net: {
      type: VoiceFeatNet,
      sample_rate: 16000,
      voice_channel: 1,
      n_fft: 512,
      n_mels: 64,
      cnn_channel: 64,
      feat_dim: 64,
    }
  head:
    net: {
      type: Prob_Linear,
      output_dim: 20370,
      prob_dim: 6790,
    }
